name: tune
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  flutter_svg: ^1.0.3
  sleek_circular_slider: ^2.0.1
  just_audio: ^0.9.20
  audio_service: ^0.18.4
  id3tag: ^0.1.0
  text_scroll: ^0.0.4
  flutter_glow: ^0.2.0
  curved_navigation_bar: ^1.0.3
  file_picker: ^4.5.1
  lottie: ^1.2.2
  liquid_swipe: ^2.1.1
  flutter_zoom_drawer: ^3.0.1
  share_plus: ^4.0.4
  sentry_flutter: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/essentials/
    - assets/icons/
    - assets/animations/
    - assets/avatars/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa/Comfortaa-Light.otf
          weight: 300
        - asset: assets/fonts/Comfortaa/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa/Comfortaa-Medium.otf
          weight: 500
        - asset: assets/fonts/Comfortaa/Comfortaa-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Comfortaa/Comfortaa-Bold.otf
          weight: 700
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis/Dosis-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Dosis/Dosis-Light.otf
          weight: 300
        - asset: assets/fonts/Dosis/Dosis-Regular.ttf
          weight: 400
        - asset: assets/fonts/Dosis/Dosis-Medium.otf
          weight: 500
        - asset: assets/fonts/Dosis/Dosis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Dosis/Dosis-Bold.otf
          weight: 700
        - asset: assets/fonts/Dosis/Dosis-ExtraBold.otf
          weight: 800
    - family: A Antara
      fonts:
        - asset: assets/fonts/A Antara/AAntaraDistance.otf

    - family: Logo
      fonts:
        - asset: assets/fonts/Svg/Logo.ttf