/// Flutter icons Logo
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Logo
///      fonts:
///       - asset: fonts/Logo.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Logo {
  Logo._();

  static const _kFontFam = 'Logo';
  static const String? _kFontPkg = null;

  static const IconData logo = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
