/// Flutter icons Logo
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
///
import 'package:flutter/widgets.dart';

class Logo {
  Logo._();

  static const _kFontFam = 'Logo';
  static const String? _kFontPkg = null;

  static const IconData logo =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
